# Generated by Django 2.1 on 2018-08-17 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='plwc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article', to='articles.ProgrammingLanguagewithCategory'),
        ),
        migrations.AlterField(
            model_name='programminglanguagewithcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pl', to='articles.Category'),
        ),
    ]
