# Generated by Django 2.1 on 2018-08-17 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20180817_0347'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='sort_order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
