# Generated by Django 2.1 on 2018-08-17 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_category_sort_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['sort_order']},
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('parentcategory', 'sort_order')},
        ),
    ]
