# Generated by Django 2.1 on 2018-08-21 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20180817_0414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='plwc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article', to='articles.ProgrammingLanguagewithCategory', unique=True),
        ),
    ]
