# Generated by Django 2.1 on 2018-08-21 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20180821_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='plwc',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='article', to='articles.ProgrammingLanguagewithCategory'),
        ),
    ]
