# Generated by Django 2.1 on 2018-08-23 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20180821_0127'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='nameslug',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
    ]
